"""
Static fallback question banks, used only when AI generation fails
(missing/invalid API key, rate limit, network error, malformed response).
Keeps the assessment flow usable even if Gemini is unavailable.
"""

FALLBACK_DSA_QUESTIONS = [
    {
        "id": 1,
        "question": "What is the time complexity of binary search on a sorted array?",
        "options": ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
        "answer": "O(log n)",
        "difficulty": "Easy",
    },
    {
        "id": 2,
        "question": "Which data structure uses LIFO (Last In First Out) order?",
        "options": ["Queue", "Stack", "Linked List", "Tree"],
        "answer": "Stack",
        "difficulty": "Easy",
    },
    {
        "id": 3,
        "question": "What is the worst-case time complexity of quicksort?",
        "options": ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"],
        "answer": "O(n^2)",
        "difficulty": "Medium",
    },
    {
        "id": 4,
        "question": "In a singly linked list, what is the time complexity to insert at the head?",
        "options": ["O(n)", "O(log n)", "O(1)", "O(n^2)"],
        "answer": "O(1)",
        "difficulty": "Easy",
    },
    {
        "id": 5,
        "question": "Which traversal of a binary tree visits the root node first?",
        "options": ["In-order", "Post-order", "Pre-order", "Level-order"],
        "answer": "Pre-order",
        "difficulty": "Medium",
    },
    {
        "id": 6,
        "question": "What is the space complexity of an adjacency matrix for a graph with V vertices?",
        "options": ["O(V)", "O(V + E)", "O(V^2)", "O(E)"],
        "answer": "O(V^2)",
        "difficulty": "Medium",
    },
    {
        "id": 7,
        "question": "Which technique does dynamic programming primarily rely on?",
        "options": [
            "Brute force",
            "Divide and conquer only",
            "Overlapping subproblems and memoization",
            "Random sampling",
        ],
        "answer": "Overlapping subproblems and memoization",
        "difficulty": "Medium",
    },
    {
        "id": 8,
        "question": "What is the time complexity of inserting into a hash table on average?",
        "options": ["O(1)", "O(n)", "O(log n)", "O(n^2)"],
        "answer": "O(1)",
        "difficulty": "Easy",
    },
    {
        "id": 9,
        "question": "Which algorithm is a classic example of the greedy approach?",
        "options": [
            "Merge Sort",
            "Dijkstra's Algorithm",
            "Quick Sort",
            "Binary Search",
        ],
        "answer": "Dijkstra's Algorithm",
        "difficulty": "Hard",
    },
    {
        "id": 10,
        "question": "What does BST stand for in the context of trees?",
        "options": [
            "Balanced Search Tree",
            "Binary Search Tree",
            "Basic Sort Tree",
            "Binary Sum Tree",
        ],
        "answer": "Binary Search Tree",
        "difficulty": "Easy",
    },
    {
        "id": 11,
        "question": "What is the time complexity to reverse an array of size n?",
        "options": ["O(1)", "O(log n)", "O(n)", "O(n^2)"],
        "answer": "O(n)",
        "difficulty": "Easy",
    },
    {
        "id": 12,
        "question": "Which algorithm is used for efficient string pattern matching?",
        "options": [
            "Bubble Sort",
            "KMP Algorithm",
            "Binary Search",
            "Dijkstra's Algorithm",
        ],
        "answer": "KMP Algorithm",
        "difficulty": "Hard",
    },
    {
        "id": 13,
        "question": "Which data structure follows FIFO (First In First Out) order?",
        "options": ["Stack", "Queue", "Tree", "Graph"],
        "answer": "Queue",
        "difficulty": "Easy",
    },
    {
        "id": 14,
        "question": "Which data structure is commonly used to evaluate postfix expressions?",
        "options": ["Queue", "Stack", "Linked List", "Hash Table"],
        "answer": "Stack",
        "difficulty": "Medium",
    },
    {
        "id": 15,
        "question": "What is the height of a balanced binary search tree with n nodes?",
        "options": ["O(n)", "O(log n)", "O(n^2)", "O(1)"],
        "answer": "O(log n)",
        "difficulty": "Medium",
    },
    {
        "id": 16,
        "question": "Breadth-First Search (BFS) traversal of a graph uses which data structure?",
        "options": ["Stack", "Queue", "Heap", "Array"],
        "answer": "Queue",
        "difficulty": "Medium",
    },
    {
        "id": 17,
        "question": "Depth-First Search (DFS) traversal of a graph is typically implemented using?",
        "options": ["Queue", "Stack or recursion", "Heap", "Hash Table"],
        "answer": "Stack or recursion",
        "difficulty": "Medium",
    },
    {
        "id": 18,
        "question": "The 0/1 Knapsack problem is a classic example of which technique?",
        "options": [
            "Greedy",
            "Dynamic Programming",
            "Backtracking only",
            "Brute force only",
        ],
        "answer": "Dynamic Programming",
        "difficulty": "Hard",
    },
    {
        "id": 19,
        "question": "Huffman coding is a classic example of which algorithmic technique?",
        "options": [
            "Dynamic Programming",
            "Greedy Algorithm",
            "Divide and Conquer",
            "Backtracking",
        ],
        "answer": "Greedy Algorithm",
        "difficulty": "Hard",
    },
    {
        "id": 20,
        "question": "What is the time complexity to access an element by index in an array?",
        "options": ["O(n)", "O(log n)", "O(1)", "O(n^2)"],
        "answer": "O(1)",
        "difficulty": "Easy",
    },
    {
        "id": 21,
        "question": "Which sorting algorithm is stable by nature?",
        "options": ["Quick Sort", "Heap Sort", "Merge Sort", "Selection Sort"],
        "answer": "Merge Sort",
        "difficulty": "Medium",
    },
    {
        "id": 22,
        "question": "Binary Search requires the input array to be:",
        "options": ["Sorted", "Unsorted", "Circular", "Doubly linked"],
        "answer": "Sorted",
        "difficulty": "Easy",
    },
    {
        "id": 23,
        "question": "In a complete binary tree, all levels are fully filled except possibly:",
        "options": [
            "The root level",
            "The last level",
            "The middle level",
            "No exceptions allowed",
        ],
        "answer": "The last level",
        "difficulty": "Medium",
    },
    {
        "id": 24,
        "question": "Which technique resolves collisions in a hash table by chaining elements in a linked list?",
        "options": [
            "Open addressing",
            "Separate chaining",
            "Linear probing",
            "Double hashing",
        ],
        "answer": "Separate chaining",
        "difficulty": "Hard",
    },
    {
        "id": 25,
        "question": "What is the time complexity of Dijkstra's algorithm using a min-heap?",
        "options": ["O(V)", "O(V + E)", "O((V + E) log V)", "O(V^2 log V)"],
        "answer": "O((V + E) log V)",
        "difficulty": "Hard",
    },
]


FALLBACK_APTITUDE_QUESTIONS = [
    {
        "id": 1,
        "question": "A train travels 120 km in 2 hours. What is its average speed?",
        "options": ["50 km/h", "60 km/h", "70 km/h", "80 km/h"],
        "answer": "60 km/h",
        "difficulty": "Easy",
    },
    {
        "id": 2,
        "question": "If the cost price of an item is Rs.800 and it is sold for Rs.920, what is the profit percentage?",
        "options": ["10%", "12%", "15%", "20%"],
        "answer": "15%",
        "difficulty": "Easy",
    },
    {
        "id": 3,
        "question": "Find the next number in the series: 2, 6, 12, 20, 30, ?",
        "options": ["40", "42", "44", "48"],
        "answer": "42",
        "difficulty": "Medium",
    },
    {
        "id": 4,
        "question": "A sum of money doubles itself in 5 years at simple interest. What is the annual rate of interest?",
        "options": ["10%", "15%", "20%", "25%"],
        "answer": "20%",
        "difficulty": "Medium",
    },
    {
        "id": 5,
        "question": "If A can complete a task in 12 days and B in 18 days, together they finish it in:",
        "options": ["6 days", "7.2 days", "8 days", "9 days"],
        "answer": "7.2 days",
        "difficulty": "Medium",
    },
    {
        "id": 6,
        "question": "Find the missing number: 5, 10, 20, 40, 80, ?",
        "options": ["120", "140", "150", "160"],
        "answer": "160",
        "difficulty": "Easy",
    },
    {
        "id": 7,
        "question": "If the ratio of boys to girls is 3:2 and there are 120 students, how many girls are there?",
        "options": ["42", "48", "50", "54"],
        "answer": "48",
        "difficulty": "Easy",
    },
    {
        "id": 8,
        "question": "A man walks 15 km north, then 20 km east. How far is he from the starting point?",
        "options": ["20 km", "25 km", "30 km", "35 km"],
        "answer": "25 km",
        "difficulty": "Medium",
    },
    {
        "id": 9,
        "question": "The probability of getting a head when tossing a fair coin is:",
        "options": ["0", "1/4", "1/2", "1"],
        "answer": "1/2",
        "difficulty": "Easy",
    },
    {
        "id": 10,
        "question": "The LCM of 12 and 18 is:",
        "options": ["24", "30", "36", "48"],
        "answer": "36",
        "difficulty": "Easy",
    },
    {
        "id": 11,
        "question": "Find the next number in the series: 3, 9, 27, 81, ?",
        "options": ["162", "216", "243", "324"],
        "answer": "243",
        "difficulty": "Easy",
    },
    {
        "id": 12,
        "question": "Pointing to a man, a woman said, 'His mother is the only daughter of my mother.' How is the woman related to the man?",
        "options": ["Sister", "Mother", "Aunt", "Grandmother"],
        "answer": "Mother",
        "difficulty": "Hard",
    },
    {
        "id": 13,
        "question": "A bag contains 4 red and 6 blue balls. What is the probability of drawing a red ball?",
        "options": ["0.2", "0.4", "0.5", "0.6"],
        "answer": "0.4",
        "difficulty": "Easy",
    },
    {
        "id": 14,
        "question": "A shopkeeper marks an item 25% above cost price and gives a 10% discount. What is his profit percentage?",
        "options": ["10%", "12.5%", "15%", "20%"],
        "answer": "12.5%",
        "difficulty": "Medium",
    },
    {
        "id": 15,
        "question": "A boat travels 30 km downstream in 2 hours and returns upstream in 3 hours. What is the speed of the boat in still water?",
        "options": ["10 km/h", "12.5 km/h", "15 km/h", "20 km/h"],
        "answer": "12.5 km/h",
        "difficulty": "Hard",
    },
    {
        "id": 16,
        "question": "Which word does NOT belong with the others?",
        "options": ["Apple", "Banana", "Carrot", "Mango"],
        "answer": "Carrot",
        "difficulty": "Easy",
    },
    {
        "id": 17,
        "question": "If CAT is coded as DBU, how is DOG coded?",
        "options": ["EPH", "EQH", "FPH", "EPI"],
        "answer": "EPH",
        "difficulty": "Medium",
    },
    {
        "id": 18,
        "question": "Find the missing term: 1, 4, 9, 16, 25, ?",
        "options": ["30", "32", "36", "49"],
        "answer": "36",
        "difficulty": "Easy",
    },
    {
        "id": 19,
        "question": "What is 15% of 240?",
        "options": ["24", "30", "36", "40"],
        "answer": "36",
        "difficulty": "Easy",
    },
    {
        "id": 20,
        "question": "Pointing to a photograph, a man says, 'She is the daughter of my grandfather's only son.' How is the woman related to the man?",
        "options": ["Sister", "Daughter", "Mother", "Niece"],
        "answer": "Sister",
        "difficulty": "Medium",
    },
    {
        "id": 21,
        "question": "A man cycles at 15 km/h and covers a certain distance in 4 hours. How long will he take to cover the same distance at 20 km/h?",
        "options": ["2 hours", "2.5 hours", "3 hours", "3.5 hours"],
        "answer": "3 hours",
        "difficulty": "Medium",
    },
    {
        "id": 22,
        "question": "An article is sold at a loss of 20% for Rs.400. What is the cost price?",
        "options": ["Rs.450", "Rs.480", "Rs.500", "Rs.520"],
        "answer": "Rs.500",
        "difficulty": "Medium",
    },
    {
        "id": 23,
        "question": "Statement: All pens are books. All books are tables. Conclusion: All pens are tables.",
        "options": ["True", "False", "Cannot be determined", "Partially true"],
        "answer": "True",
        "difficulty": "Medium",
    },
    {
        "id": 24,
        "question": "Find the odd one out: 8, 27, 64, 100, 125",
        "options": ["27", "64", "100", "125"],
        "answer": "100",
        "difficulty": "Medium",
    },
    {
        "id": 25,
        "question": "The average of 5 numbers is 20. If one number is excluded, the average becomes 18. What is the excluded number?",
        "options": ["20", "24", "28", "32"],
        "answer": "28",
        "difficulty": "Hard",
    },
]
