# Generated by Django 6.0.3 on 2026-07-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='otp_otpveri_email_e7f9cf_idx',
            old_name='otp_otpveri_email_idx',
        ),
    ]
