# Generated by Django 6.0.3 on 2026-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_extraction_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='extraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
    ]
